export * from './base';
export * from './news';
export * from './events';
export * from './media';
export * from './academics';
export * from './profiles';
export * from './admission';
export * from './users';
export * from './dashboard';
